### ISSUE TITLE
it doesnt dance it just looks at me 😒😒

### ISSUE THREAD

**Issue by yallseetheshoes** [GhoulMage/SassyCoilhead#1]
i get this error like 10000000 times
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SassyCoilheadMod.CoilheadDanceCheck.NearAnyPlayer () (at <4b114e6e46cf44b48aeb3a161168f3a7>:IL_000E)
SassyCoilheadMod.CoilheadDanceCheck.LateUpdate () (at <4b114e6e46cf44b48aeb3a161168f3a7>:IL_0091)

**Comment by GhoulMage** [comment]
I need some info beforehand. Do you have any mods that might modify the coilhead (itself or its behaviour) or that might make you able to kill them?

> i get this error like 10000000 times [Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: SassyCoilheadMod.CoilheadDanceCheck.NearAnyPlayer () (at <4b114e6e46cf44b48aeb3a161168f3a7>:IL_000E) SassyCoilheadMod.CoilheadDanceCheck.LateUpdate () (at <4b114e6e46cf44b48aeb3a161168f3a7>:IL_0091)

**Comment by GhoulMage** [comment]
I added some sanity checks to avoid this situation. Since I can't replicate the error I'll mark as fixed and hope it was enough.
